### ISSUE TITLE
Align tooltips to pixels

### ISSUE THREAD

**Issue by athyuttamre** [primer/primer-tooltips#2]
When tooltips are translated by 50%, sometimes they get aligned to half pixels. This causes the text to become blurry. I believe the only way to ensure this is to make sure the width of the entire tooltip is even.

Is there any way to avoid blurry text?

**Comment by jonrohan** [comment]
I've seen this, so I know it's a bug, but I can't figure it out myself. I've seen where it depends on the length of the text. I'll leave this issue open, and ask for any help insight from passer-bys.

**Comment by cormacrelf** [comment]
translateX/Y's sub-pixel rounding is implemented inconsistently across browsers. Some browsers will round it, some won't: http://martinkool.com/post/27618832225/beware-of-half-pixels-in-css

The only complete solution is to replace all CSS translate styles with something else.
