### ISSUE TITLE
On mobile, tooltips don't disappear after pressing button

### ISSUE THREAD

**Issue by AlMcKinlay** [primer/primer-tooltips#4]
So, on [the lounge](https://github.com/thelounge/lounge) we are using these tooltips for our buttons. However, we have noticed that when you press a button with a tooltip, the tooltip seems to keep until you give focus to something else (thelounge/lounge#585).

I reckon this is because it uses the focus attribute as one of the options for choosing whether you show a tooltip.

[Here is an example of us using the tooltip on a button.](https://github.com/thelounge/lounge/blob/721765511062608526fa70a87e72980c0dfd14c9/client/views/chat.tpl) Are we missing anything obvious?

**Comment by jonrohan** [comment]
This is currently expected behavior, but we may revisit this in the near future when we take on responsive

**Comment by astorije** [comment]
For what our opinion is worth, we had to disable the tooltips on the mobile version of https://thelounge.github.io/ due to this, so we'll keep an eye out on your potential improvements :)
