### ISSUE TITLE
Partially supported value for the CSS property "word-break"

### ISSUE THREAD

**Issue by r4nd0m** [primer/primer-tooltips#6]
Where:
in /lib/tooltips.scss:200

What:
"word-break: break-word;" is being supported only by Chrome/Safari, not FF/IE/Edge
https://developer.mozilla.org/en-US/docs/Web/CSS/word-break
http://caniuse.com/#search=word-break

Possible fixes:
1. Change to "word-break: break-all"
2. Use word-wrap instead of word-break

**Comment by muan** [comment]
Thanks! This is fixed in `0.5.4`.
